### ISSUE TITLE
Bob Tech Save error on load

### ISSUE THREAD

**Issue by schosin** [Pandemoneus/Farlands#2]
Unknown key:"Error while running the on_load: **bobtechsave**/control.lua:32: attempt to index global 'game' (a nil value)"

We disabled for now. Could load map fine after updating, friend couldn't join and after I saved and attempted to load the save I got the error as well.

**Comment by Pandemoneus** [comment]
I can confirm this bug. Reported it to Bobingabout.

**Comment by Pandemoneus** [comment]
Fixed in 0.1.5.
