### ISSUE TITLE
Are all mods still original?

### ISSUE THREAD

**Issue by dionysius** [Pandemoneus/Farlands#6]
Pretty much title. Or do you have changed the config of specific mod (=modified) or even changed the code (=patched)?

If yes, I'd like to know and also maybe reflect this in the readme modlist (e.g. M for modified and P for patched or so)

**Comment by Pandemoneus** [comment]
I have changed the configs.
Bobs: Merged modules disabled.
Macromanaged Turrets: Tick time from 30 to 120.
Map Labels: Added all custom resources.
RSO: Custom settings. Compare with original, if you want.
ScienceCostTweaker: DifficultyEvo = "noadjustment"

That's about it, I think.
