### ISSUE TITLE
Water field eat my Base

### ISSUE THREAD

**Issue by Kettzer** [Pandemoneus/Farlands#8]
hi, I have update the mod pack. I have 2 extra mods "Boxing" and  "TimeTools".

If I have load my old 14.5 Savegame and play it, after a while. the water fields are growing and eat the land. 
It eats some of my machines. I start a new world and today as I load the 4h gameplay eat the water some land.

and that's not only one spot on this map i have seen this.

Screenshots: 
![before](https://cloud.githubusercontent.com/assets/24864874/21582435/74ee24d6-d057-11e6-88b1-3cfc5f8711ce.jpg)
![after](https://cloud.githubusercontent.com/assets/24864874/21582436/781fb426-d057-11e6-83a7-58ba2a26b0db.jpg)

**Comment by Pandemoneus** [comment]
Yes, global warming causes water levels to rise and swallow the land. If you want to prevent that, you will have to put walls around water or fill them in using landfill.
Also, instead of the water pump, you can use the water well.
